# Generated by Django 5.1.3 on 2024-11-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("tester", "Tester"),
                    ("Developer", "developer"),
                    ("manager", "Manager"),
                ],
                default="tester",
                max_length=20,
            ),
        ),
    ]
