# Generated by Django 5.1.3 on 2024-12-05 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defect_registry", "0003_alter_project_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="defect_registry.project",
            ),
        ),
    ]
